export const CITIES = [
"Kathmandu","Pokhara","Lalitpur","Bharatpur","Biratnagar","Birgunj",
"Ghorahi","Tulsipur","Dharan","Itahari","Janakpurdham","Hetauda",
"Kalaiya","Jitpursimara","Butwal","Nepalgunj","Dhangadhi",
"Birendranagar","Godawari","Siddharthanagar","Triyuga","Kohalpur",
"Tilottama","Lahan","Rajbiraj","Siraha","Malangwa","Gaur",
"Kapilvastu","Sandhikharka","Tansen","Baglung","Waling","Putalibazar",
"Gorkha","Besishahar","Dhulikhel","Banepa","Panauti","Bhaktapur",
"Kirtipur","Madhyapur Thimi","Tokha","Budhanilkantha","Gokarneshwar",
"Tarakeshwar","Chandragiri","Dakshinkali","Shankharapur","Nagarkot",
"Changunarayan","Suryabinayak","Nilkantha","Dhunibeshi","Ratnanagar",
"Khairhani","Rapti","Kalika","Madi","Bhadrapur","Birtamode","Damak",
"Kankai","Mechinagar","Arjundhara","Shivasatakshi","Gauradaha",
"Urlabari","Rangeli","Pathari-Shanishchare","Letang","Belbari",
"Sunwarshi","Sundar Haraicha","Inaruwa","Duhabi","Ramdhuni",
"Ilam","Phidim","Taplejung","Fungling","Dhankuta","Pakhribas",
"Hile","Bhojpur","Shadananda","Khandbari","Chainpur","Dharmadevi",
"Barahakshetra","Belaka","Udayapurgadhi","Katari","Chaudandigadhi",
"Bhimeshwar","Jiri","Manthali","Ramechhap","Melamchi","Barhabise",
"Chautara","Indrawati","Panchkhal","Mandandeupur","Namobuddha",
"Kamalamai","Dudhauli","Hariwan","Lalbandi","Ishworpur","Bagmati",
"Chandrapur","Gujara","Bardibas","Gaushala","Jaleshwar","Manara",
"Matihani","Bhangaha","Balawa","Loharpatti","Ramgopalpur",
"Aurahi","Bideha","Kshireshwarnath","Dhanushadham","Sabaila",
"Ganeshman Charnath","Mithila","Nagarain","Kamala","Bhagwanpur",
"Mahagadhimai","Simraungadh","Kolhabi","Nijgadh","Jeetpur",
"Parwanipur","Pokhariya","Bahudarmai","Parsagadhi","Bansgadhi",
"Gulariya","Madhuwan","Rajapur","Thakurbaba","Tikapur","Lamki",
"Ghodaghodi","Bhajani","Janaki","Krishnapur","Shuklaphanta",
"Belauri","Punarbas","Mahendranagar","Bedkot","Dodhara Chandani",
"Amargadhi","Parshuram","Dasharathchand","Purchaudi","Patan",
"Melauli","Jayaprithvi","Chainpur Bajhang","Talkot","Shital",
"Dipayal Silgadhi","Shikhar","Budhiganga","Sanphebagar",
"Kamalamai","Dhangadhi","Attariya","Lamahi","Gadhawa","Banganga",
"Kapilvastu","Shivaraj","Krishnanagar","Maharajganj","Ramgram",
"Sunwal","Devdaha","Sainamaina","Butwal","Tilottama",
"Resunga","Musikot","Chandrakot","Isma","Ruru","Bhurigaun",
"Triveni","Salyan","Sharada","Bagchaur","Bangad Kupinde",
"Jumla","Chandannath","Narayan","Dullu","Aathabis","Chamunda",
"Mahakali","Shailyashikhar","Bhimdatta","Bedkot"
];